# Change these first
owner: shaowenchen # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: www.chenshaowen.com
    url: https://www.chenshaowen.com
    icon: https://www.chenshaowen.com/favicon.ico
    maxResponseTime: 2000
  - name: www.chenshaowen.com-tcp
    check: "tcp-ping"
    url: www.chenshaowen.com
    port: 443
    icon: https://www.chenshaowen.com/favicon.ico
    maxResponseTime: 2000

status-website:
  cname: upptime.chenshaowen.com
  logoUrl: https://www.chenshaowen.com/logo.png
  name: Upptime
