# Change these first
owner: shaowenchen # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: www.chenshaowen.com
    url: https://www.chenshaowen.com
    maxResponseTime: 1000
  - name: chatgpt.chenshaowen.com
    url: https://chatgpt.chenshaowen.com
    maxResponseTime: 1000
  - name: network
    url: $NETWORK_URL
    maxResponseTime: 1000
    expectedStatusCodes:
      - 400
  - name: account
    url: $ACCOUNT_URL
    maxResponseTime: 1000
  - name: accountapi
    url: $ACCOUNTAPI_URL
    maxResponseTime: 1000
  - name: payment
    url: $PAYMENT_URL
    maxResponseTime: 1000
  - name: paymentapi
    url: $PAYMENTAPI_URL
    maxResponseTime: 1000
  - name: chainsapi
    url: $CHAINSAPI_URL
    maxResponseTime: 1000
  - name: upload
    url: $UPLOAD_URL
    maxResponseTime: 1000
  - name: uploadapi
    url: $UPLOADAPI_URL
    maxResponseTime: 1000
  - name: data
    url: $DATA_URL
    maxResponseTime: 1000
  - name: dataapi
    url: $DATAAPI_URL
    maxResponseTime: 1000
  - name: llmapi
    url: $LLMAPI_URL
    maxResponseTime: 1000

status-website:
  cname: upptime.chenshaowen.com
  logoUrl: https://www.chenshaowen.com/logo.png
  name: Upptime
